=== DionisisChar/Xml/xml schemas/Order_Scenario/Order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/Order"
	xmlns:tns="http://www.example.org/Order" elementFormDefault="qualified">

	<element name="Order" type="tns:Order" />

	<complexType name="Order">
		<sequence>
			<element name="Product" type="tns:Product"
				maxOccurs="unbounded" />
			<element name="Customer" type="tns:Customer" />
		</sequence>
		<attribute name="id" type="tns:IdRestriction" use="required"></attribute>
	</complexType>

	<complexType name="Customer">
		<choice>
			<element name="name" type="string" />
			<element name="phone" type="string" minOccurs="0" />
		</choice>
		<attribute name="id" type="int" use="required" />
	</complexType>

	<complexType name="Product">
		<sequence>
			<element name="name" type="tns:String20Characters" />
			<element name="description" type="tns:String100Chars" />
			<element name="price" type="int" />
			<element name="category" type="tns:AllowedCategory" />
		</sequence>

		<attribute name="id" type="int" use="required" />
	</complexType>

	<simpleType name="String20Characters">
		<restriction base="string">
			<maxLength value="20" />
		</restriction>
	</simpleType>

	<simpleType name="String100Chars">
		<restriction base="string">
			<maxLength value="100" />
		</restriction>
	</simpleType>

	<simpleType name="AllowedCategory">
		<restriction base="string">
			<enumeration value="books" />
			<enumeration value="electronics" />
			<enumeration value="shoes" />
		</restriction>
	</simpleType>

	<simpleType name="IdRestriction">
		<restriction base="int">
			<maxInclusive value="50"></maxInclusive>
		</restriction>
	</simpleType>
</schema>

=== DionisisChar/Xml/xml schemas/Order_Scenario/Order.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Order id="50" xmlns:tns="http://www.example.org/Order"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Order Order.xsd ">
	<tns:Product id="51">
		<tns:name>tns:name</tns:name>
		<tns:description>tns:description</tns:description>
		<tns:price>0</tns:price>
		<tns:category>electronics</tns:category>
	</tns:Product>
	<tns:Customer id="51">
		<tns:name>Dion</tns:name>
	</tns:Customer>
</tns:Order>
